#include <algorithm>
#include <array>
#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <numeric>
#include <tuple>
#include <vector>

// Exact orbit enumeration of codimension-two kernels in the standard
// [4x4,12,2]_2 Gabidulin code.  A kernel is represented by its 2-dimensional
// annihilator in the 12-dimensional message dual.  We use the rank-preserving
// automorphisms generated by output scaling, input scaling, and Frobenius.

static unsigned gf_mul(unsigned a,unsigned b){
  unsigned r=0;
  while(b){
    if(b&1) r^=a;
    b>>=1; a<<=1;
    if(a&16) a=(a&15)^3; // x^4+x+1
  }
  return r;
}
static unsigned gf_sq(unsigned a){return gf_mul(a,a);}

static unsigned transform_message(unsigned x,int kind){
  unsigned a=x&15,b=(x>>4)&15,c=(x>>8)&15;
  if(kind==0){ // output scaling by primitive element 2
    a=gf_mul(2,a); b=gf_mul(2,b); c=gf_mul(2,c);
  } else if(kind==1){ // input scaling by primitive element 2
    a=gf_mul(a,2); b=gf_mul(b,gf_sq(2)); c=gf_mul(c,gf_sq(gf_sq(2)));
  } else { // simultaneous input/output Frobenius conjugation
    a=gf_sq(a); b=gf_sq(b); c=gf_sq(c);
  }
  return a|(b<<4)|(c<<8);
}

static unsigned gf_matrix(unsigned message){
  unsigned a=message&15,b=(message>>4)&15,c=(message>>8)&15,m=0;
  for(int col=0;col<4;++col){
    unsigned x=1U<<col,x2=gf_sq(x),x4=gf_sq(x2);
    unsigned y=gf_mul(a,x)^gf_mul(b,x2)^gf_mul(c,x4);
    m|=y<<(4*col);
  }
  return m;
}
static int rank4(unsigned m){
  std::array<unsigned,4> rows{};
  for(int r=0;r<4;++r){
    for(int c=0;c<4;++c) rows[r]|=((m>>(4*c+r))&1U)<<c;
  }
  int k=0;
  for(int b=0;b<4;++b){
    int p=-1;for(int r=k;r<4;++r)if((rows[r]>>b)&1U){p=r;break;}
    if(p<0)continue;std::swap(rows[k],rows[p]);
    for(int r=k+1;r<4;++r)if((rows[r]>>b)&1U)rows[r]^=rows[k];
    ++k;
  }
  return k;
}

struct DSU{
  std::vector<uint32_t> p,sz;
  explicit DSU(size_t n):p(n),sz(n,1){std::iota(p.begin(),p.end(),0);}
  uint32_t get(uint32_t x){while(p[x]!=x){p[x]=p[p[x]];x=p[x];}return x;}
  void unite(uint32_t a,uint32_t b){a=get(a);b=get(b);if(a==b)return;if(sz[a]<sz[b])std::swap(a,b);p[b]=a;sz[a]+=sz[b];}
};

static uint32_t key_span(unsigned x,unsigned y){
  std::array<unsigned,3> z{x,y,x^y};std::sort(z.begin(),z.end());
  return (z[0]<<12)|z[1];
}

int main(int argc,char**argv){
  const char* outfile=argc>1?argv[1]:"standard_d_kernel_orbits.jsonl";
  std::vector<uint16_t> aa,bb;
  std::vector<int32_t> index(1U<<24,-1);
  aa.reserve(2794155);bb.reserve(2794155);
  for(unsigned a=1;a<4096;++a)for(unsigned b=a+1;b<4096;++b){
    unsigned c=a^b;if(c<=b)continue;
    uint32_t key=(a<<12)|b;
    index[key]=(int32_t)aa.size();aa.push_back(a);bb.push_back(b);
  }
  std::cerr<<"subspaces "<<aa.size()<<"\n";
  if(aa.size()!=2794155) return 2;

  std::array<std::array<uint16_t,4096>,3> fmap{};
  for(int kind=0;kind<3;++kind){
    std::array<uint16_t,4096> inv{};
    for(unsigned x=0;x<4096;++x) inv[transform_message(x,kind)]=x;
    for(unsigned l=0;l<4096;++l){
      unsigned lp=0;
      for(int j=0;j<12;++j) if(std::popcount(l & inv[1U<<j])&1) lp|=1U<<j;
      fmap[kind][l]=lp;
    }
  }
  DSU dsu(aa.size());
  for(uint32_t i=0;i<aa.size();++i){
    for(int g=0;g<3;++g){
      uint32_t key=key_span(fmap[g][aa[i]],fmap[g][bb[i]]);
      int32_t j=index[key];if(j<0){std::cerr<<"bad key\n";return 3;}
      dsu.unite(i,(uint32_t)j);
    }
  }

  std::vector<unsigned> rank2;
  for(unsigned x=1;x<4096;++x)if(rank4(gf_matrix(x))==2)rank2.push_back(x);
  if(rank2.size()!=525){std::cerr<<"bad rank2 "<<rank2.size()<<"\n";return 4;}
  std::vector<std::tuple<int,uint32_t,unsigned,unsigned,unsigned>> reps;
  for(uint32_t i=0;i<aa.size();++i)if(dsu.get(i)==i){
    int cnt=0;
    for(auto x:rank2)if(!(std::popcount(x&aa[i])&1)&&!(std::popcount(x&bb[i])&1))++cnt;
    reps.emplace_back(cnt,dsu.sz[i],aa[i],bb[i],aa[i]^bb[i]);
  }
  std::sort(reps.begin(),reps.end());
  std::ofstream f(outfile);
  for(auto [cnt,os,a,b,c]:reps)
    f<<"{\"rank2_count\":"<<cnt<<",\"orbit_size\":"<<os
     <<",\"span\":["<<a<<","<<b<<","<<c<<"]}\n";
  std::cerr<<"orbits "<<reps.size()<<"\n";
  int last=-1,n=0;uint64_t mass=0;
  for(auto [cnt,os,a,b,c]:reps){
    if(cnt!=last){if(last>=0)std::cerr<<"count "<<last<<" orbits "<<n<<" mass "<<mass<<"\n";last=cnt;n=0;mass=0;}
    ++n;mass+=os;
  }
  if(last>=0)std::cerr<<"count "<<last<<" orbits "<<n<<" mass "<<mass<<"\n";
}
